config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

#mapping of url to controller
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:user_id/blogs' => 'blogs#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :blogs do
    resources :posts do
      #except: :new, :edit -- dont make routes for these commands
      resources :comments, only: [:create, :update, :destroy]
      resources :categories, only: [:create, :destroy, :search]

      post '/star' => 'stars#star'
      delete '/star' => 'stars#unstar'
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  self.table_name = "blog"

  def author_name
        author = User.find_by_sql("SELECT * FROM user WHERE id = #{self.owner};").first
        author.name
  end

  def posts
    Post.find_by_sql "SELECT * FROM post WHERE blog = #{self.id};"
  end

  # def posts_search(search)
  #   Post.find_by_sql "SELECT * FROkoM post WHERE blog = #{self.id} AND title LIKE %#{search}%;"
  # end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
#shows ONE blog page
  def show
    page_size = 6
    unless params[:page]
      params[:page] = 1
    end

    @blog = Blog.find_by_sql("SELECT * FROM blog where id = #{params[:id]};").first
    @posts = Post.find_by_sql "SELECT * FROM post WHERE blog = #{@blog.id} LIMIT #{(params[:page].to_i - 1) * page_size}, #{page_size + 1};"

    if params[:search]
      @posts = Post.search(params[:search], @blog.id, page_size, params[:page].to_i)
    end

    @has_prev = params[:page].to_i > 1
    @has_next = @posts.length > page_size
    @posts = @posts[0...page_size]
  end

#for manage and browse blogs
  def index
    page_size = 6
    unless params[:page]
      params[:page] = 1
    end

    if params[:user_id]
      @blogs = Blog.find_by_sql "SELECT * FROM blog WHERE owner = #{params[:user_id]} AND visible = true LIMIT #{(params[:page].to_i - 1) * page_size}, #{page_size + 1};"
    else
      @blogs = Blog.find_by_sql "SELECT * FROM blog WHERE visible = true LIMIT #{(params[:page].to_i - 1) * page_size}, #{page_size + 1};"
    end
    @has_prev = params[:page].to_i > 1
    @has_next = @blogs.length > page_size
    @blogs = @blogs[0...page_size]
  end

  def new
  end

  def create
    if blog_params[:title].blank? || blog_params[:description].blank?
      render(json: "Error: blank entries") and return
    end

    cols = blog_params.keys.join(", ")
    vals = blog_params.values.map{|val| %Q(#{Blog.sanitize(val)}) }.join(", ")
    Blog.connection.execute("INSERT INTO blog (owner, #{cols}) VALUES (#{current_user.id}, #{vals});")
    blog = Blog.find_by_sql("SELECT * FROM blog WHERE owner = #{current_user.id} ORDER BY id DESC LIMIT 1;").first
    redirect_to "/blogs/#{blog.id}"
  end

  def edit
    @blog = Blog.find_by_sql("SELECT * FROM blog where id = #{params[:id]};").first
  end

  def update
    if blog_params[:title].blank? || blog_params[:description].blank?
      render(json: "Error: blank entries") and return
    end
    
    updates = blog_params.map{|k, v| [%Q(#{k}=#{Blog.sanitize(v)})]}.join(", ")
    Blog.connection.execute("UPDATE blog SET #{updates} WHERE id = #{params[:id]};")
    redirect_to "/blogs/#{params[:id]}"
  end

  def destroy
    Blog.connection.execute("UPDATE blog SET visible=false WHERE id = #{params[:id]};")
    redirect_to "/blogs"
  end

private

  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="edit-blog">
    <h1>Edit Blog</h1>

    <div class="edit-blog-form">
        <%= form_for :blog, url: "/blogs/#{@blog.id}", method: :put do |f| %>

        <div class="row">
            <%= f.text_field :title, placeholder: "Title", class: "blog-title" %>
        </div>
        <div class="row">
            <%= f.text_area :description, placeholder: "Description" %>
        </div>
        <div class="row">
            <%= f.submit "Submit", class: "submit-button" %>
        </div>
        <% end %>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="browse-blog">
    <h1>BROWSE BLOGS
    </h1>

    <div class="blog-collection row">
        <% @blogs.each do |blog| %>
        <div class="blog-card">
            <div class="blog-title">
                <h3><%=blog.title%></h3>
                <h4>owned by:
                    <%=blog.author_name%></h4>
            </div>
            <div class="blog-description">
                <h5><%= blog.description[0..300].gsub(/\s\w+\s*$/, '...') %></h5>
                <div class="visit-edit-btn">
                    <%= link_to('Visit', "/blogs/#{blog.id}", :class => "btn btn-primary", id: "visit")  %>
                    <% if current_user && (blog.owner == current_user.id || current_user.is_admin) %>
                    <%= link_to('Edit', "/blogs/#{blog.id}/edit", :class => "btn btn-primary", id: "edit")  %>
                    <%= link_to('Delete', "/blogs/#{blog.id}", method: :delete, :class => 'btn btn-danger')  %>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>

    <div class="prev-next row">
            <% if @has_prev %>
            <%= link_to "Prev", "#{request.env['PATH_INFO']}?page=#{params[:page].to_i - 1}", :class => "btn btn-default" %>
            <% end %>
            <% if @has_next %>
            <%= link_to "Next", "#{request.env['PATH_INFO']}?page=#{params[:page].to_i + 1}", :class => "btn btn-default pull-right" %>
            <% end %>
    </div>
</div>

app/views/blogs/new.html.erb
<div class="new-blog">
    <h1>New Blog</h1>

    <div class="new-blog-form">
        <%= form_for :blog, url: '/blogs' do |f| %>

        <div class="row">
            <%= f.text_field :title, placeholder: "Title", class: "blog-title" %>
        </div>
        <div class="row">
            <%= f.text_area :description, placeholder: "Description" %>
        </div>
        <div class="row">
            <%= f.submit "Submit", class: "submit-button" %>
        </div>
        <% end %>
    </div>
</div>

app/views/blogs/show.html.erb
<!-- <div class="search-category">
<%= form_tag(blog_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search", :name => nil) %>
<% end %>
</div> -->

<div class="blog">
    <% if current_user && (@blog.owner == current_user.id || current_user.is_admin()) %>
    <div class="pull-left">
        <div class="new-post">
            <%= link_to('New Post', "/blogs/#{@blog.id}/posts/new", :class => 'btn btn-primary')  %>
            <%= link_to('Edit', "/blogs/#{@blog.id}/edit", :class => "btn btn-primary", id: "edit")  %>
            <%= link_to('Delete', "/blogs/#{@blog.id}", method: :delete, :class => 'btn btn-danger')  %>
        </div>
    </div>
    <% end %>
    <div class="pull-right">
        <div class="search-posts">
            <%= form_tag "/blogs/#{@blog.id}", id: "search-form", :method => 'get' do %>
            <p>
                <%= text_field_tag :search, params[:search], placeholder: "Search for a Post" %>
                <button type="submit" class="btn btn-default">
                   <i class="fa fa-search"></i>
                </button>
            </p>
            <% end %>
        </div>
    </div>

    <div class="blog-details">
        <h1><%= @blog.title %></h1>
        <h3>owned by:
            <%= @blog.author_name%></h3>
        <h4><%= @blog.description %></h4>
    </div>
    
    <div class="post-collection row">
        <% @posts.each do |post| %>
        <div class="col-md-6" id="post-card">
            <div class="post-title">
                <h2 class="post-title-text"><%= post.title %></h2>
                <p class="post-author"><%= post.author_name %>
                    |
                    <%= post.format_date %></p>
                <div class="star">
                    <button class="star-btn" data-url=<%= "/blogs/#{@blog.id}/posts/#{post.id}" %>>
                        <% if current_user && post.starred_by(current_user) %>
                        <i class="fa fa-star fa-lg"></i>
                    <% else %>
                        <i class="fa fa-star-o fa-lg"></i>
                        <% end %>
                    </button>
                    <span class="star-btn-text"><%= post.star_count %></span>
                </div>
            </div>
            <div class="post-details">
                <h3><%= post.body[0..300].gsub(/\s\w+\s*$/, '...') %></h3>
                <div class="visit-edit-btn">
                    <%= link_to('Visit', "/blogs/#{@blog.id}/posts/#{post.id}", :class => 'btn btn-primary')  %>
                    <% if current_user && (post.author == current_user.id || current_user.is_admin()) %>
                    <%= link_to('Edit', "/blogs/#{@blog.id}/posts/#{post.id}/edit", :class => 'btn btn-default')  %>
                    <%= link_to('Delete', "/blogs/#{@blog.id}/posts/#{post.id}", method: :delete, :class => 'btn btn-danger')  %>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>

    <div class="prev-next row">
            <% if @has_prev %>
            <%= link_to "Prev", "#{request.env['PATH_INFO']}?page=#{params[:page].to_i - 1}", :class => "btn btn-default" %>
            <% end %>
        <% if @has_next %>
            <%= link_to "Next", "#{request.env['PATH_INFO']}?page=#{params[:page].to_i + 1}", :class => "btn btn-default pull-right" %>
            <% end %>
    </div>
</div>